name: CaptureZones
version: '1.1.2'
main: com.logichh.capturezones.CaptureZones
api-version: '1.20'
softdepend: [Towny, Dynmap, WorldGuard, PlaceholderAPI, Dynmap-Towny, MythicMobs, BlueMap]
authors: [LogicHH]
description: A plugin that adds capturable zones with optional map integrations

commands:
  capturezones:
    description: Main command for CaptureZones
    usage: /capturezones [subcommand]
    aliases: [capturepoint, cap]

permissions:
  capturezones.use:
    description: Allows using basic CaptureZones commands (list, info, capture)
    default: true

  capturezones.admin:
    description: Allows using all admin CaptureZones commands
    default: op
    children:
      capturezones.use: true
      capturezones.admin.create: true
      capturezones.admin.delete: true
      capturezones.admin.reload: true
      capturezones.admin.migrate: true
      capturezones.admin.stop: true
      capturezones.admin.forcecapture: true
      capturezones.admin.reset: true
      capturezones.admin.setitempayout: true
      capturezones.admin.timewindow: true
      capturezones.admin.togglechat: true
      capturezones.admin.stats: true
      capturezones.admin.stats.nocooldown: true
      capturezones.admin.zoneconfig: true
      capturezones.admin.zoneconfig.set: true
      capturezones.admin.zoneconfig.reset: true
      capturezones.admin.zoneconfig.reload: true
      capturezones.admin.shop: true
      capturezones.admin.shop.restock: true
      capturezones.admin.koth: true
      capturezones.admin.update-notify: true

  capturezones.admin.create:
    description: Allows creating capture zones
    default: op

  capturezones.admin.delete:
    description: Allows deleting capture zones
    default: op

  capturezones.admin.reload:
    description: Allows reloading the plugin configuration
    default: op

  capturezones.admin.migrate:
    description: Allows running schema repair to add missing config/data keys
    default: op

  capturezones.admin.stop:
    description: Allows stopping active captures
    default: op

  capturezones.admin.forcecapture:
    description: Allows forcing a town to capture a point
    default: op

  capturezones.admin.reset:
    description: Allows resetting a point to unclaimed state
    default: op

  capturezones.admin.setitempayout:
    description: Allows setting a point's item payout
    default: op

  capturezones.admin.timewindow:
    description: Allows managing time windows for capture zones
    default: op

  capturezones.admin.togglechat:
    description: Allows toggling capture chat messages
    default: op

  capturezones.admin.stats:
    description: Allows managing statistics (remove, reset)
    default: op

  capturezones.admin.stats.nocooldown:
    description: Bypasses the cooldown for /cap stats command
    default: op

  capturezones.admin.zoneconfig:
    description: Allows managing zone-specific configs
    default: op

  capturezones.admin.zoneconfig.set:
    description: Allows setting zone-specific config values
    default: op

  capturezones.admin.zoneconfig.reset:
    description: Allows resetting zone configs to defaults
    default: op

  capturezones.admin.zoneconfig.reload:
    description: Allows reloading zone configs
    default: op

  capturezones.shop.use:
    description: Allows using zone shops
    default: true

  capturezones.admin.shop:
    description: Allows managing zone shops (edit, enable/disable, reload)
    default: op

  capturezones.admin.shop.restock:
    description: Allows manually restocking zone shops
    default: op

  capturezones.admin.koth:
    description: Allows controlling KOTH events
    default: op


